### ISSUE TITLE
Failed commit with  comment that "chore: Update release-it.json for version v${version}."

### ISSUE THREAD

**Issue by ryota-murakami** [laststance/git-commit-gpt#2]
```node
ryota.murakami@MacBook-Pro ~/l/eslint-config-ts-prefixer (main)> git gpt commit
✔ chore: Update release-it.json for version v${version}. … yes
error: pathspec 'Update' did not match any file(s) known to git
error: pathspec 'release-it.json' did not match any file(s) known to git
error: pathspec 'for' did not match any file(s) known to git
error: pathspec 'version' did not match any file(s) known to git
error: pathspec 'v' did not match any file(s) known to git
node:internal/errors:865
  const err = new Error(message);
              ^

Error: Command failed: git commit -m chore: Update release-it.json for version v${version}
error: pathspec 'Update' did not match any file(s) known to git
error: pathspec 'release-it.json' did not match any file(s) known to git
error: pathspec 'for' did not match any file(s) known to git
error: pathspec 'version' did not match any file(s) known to git
error: pathspec 'v' did not match any file(s) known to git

    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at gptCommit (file:///Users/ryota.murakami/Library/pnpm/global/5/.pnpm/@laststance+git-gpt-commit@0.5.0/node_modules/@laststance/git-gpt-commit/index.js:67:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.<anonymous> (file:///Users/ryota.murakami/Library/pnpm/global/5/.pnpm/@laststance+git-gpt-commit@0.5.0/node_modules/@laststance/git-gpt-commit/index.js:81:7) {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(322) [Uint8Array] [
      101, 114, 114, 111, 114,  58,  32, 112,  97, 116, 104, 115,
      112, 101,  99,  32,  39,  85, 112, 100,  97, 116, 101,  39,
       32, 100, 105, 100,  32, 110, 111, 116,  32, 109,  97, 116,
       99, 104,  32,  97, 110, 121,  32, 102, 105, 108, 101,  40,
      115,  41,  32, 107, 110, 111, 119, 110,  32, 116, 111,  32,
      103, 105, 116,  10, 101, 114, 114, 111, 114,  58,  32, 112,
       97, 116, 104, 115, 112, 101,  99,  32,  39, 114, 101, 108,
      101,  97, 115, 101,  45, 105, 116,  46, 106, 115, 111, 110,
       39,  32, 100, 105,
      ... 222 more items
    ]
  ],
  pid: 43118,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(322) [Uint8Array] [
    101, 114, 114, 111, 114,  58,  32, 112,  97, 116, 104, 115,
    112, 101,  99,  32,  39,  85, 112, 100,  97, 116, 101,  39,
     32, 100, 105, 100,  32, 110, 111, 116,  32, 109,  97, 116,
     99, 104,  32,  97, 110, 121,  32, 102, 105, 108, 101,  40,
    115,  41,  32, 107, 110, 111, 119, 110,  32, 116, 111,  32,
    103, 105, 116,  10, 101, 114, 114, 111, 114,  58,  32, 112,
     97, 116, 104, 115, 112, 101,  99,  32,  39, 114, 101, 108,
    101,  97, 115, 101,  45, 105, 116,  46, 106, 115, 111, 110,
     39,  32, 100, 105,
    ... 222 more items
  ]
}

Node.js v18.18.2
```

**Comment by ryota-murakami** [comment]
fixed https://github.com/laststance/git-commit-gpt/commit/201ed8294d2b0db075b115ef33cd3086ba979d36
